In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [42]:
def schwefel(X):  # minimum 0 at (420.9687,420.9687,...,420.9687)
    offset = 0
    shape = X.shape
    if len(shape)>1:
        return 418.9829 * shape[1] - np.sum((X+offset)*np.sin(np.sqrt(np.abs(X+offset))),axis=1)
    else: 
        return 418.9829 * shape[0] - np.sum((X+offset)*np.sin(np.sqrt(np.abs(X+offset))))

In [71]:
def dixon_price(X): # minimum 0 at xi = 2**(-(2**i-2)/2**i)
    offset = 0
    shape = X.shape
    if len(shape)>1:
        return (X[:,[0]]-1)**2 + np.sum(np.arange(1,shape[1])*(2*(X[:,1:]+offset)**2-X[:,:-1]-offset)**2,axis=1)
    else: 
        return (X[:,[0]]-1)**2 + np.sum(np.arange(1,shape[0])*(2*(X[:,1:]+offset)**2-X[:,:-1]-offset)**2)

In [76]:
a = np.random.randint(0,5,(5,3))
a

array([[3, 0, 0],
       [3, 1, 2],
       [3, 1, 2],
       [0, 1, 0],
       [1, 4, 4]])

In [77]:
b = np.expand_dims(np.arange(5),axis=1)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [78]:
a+b

array([[3, 0, 0],
       [4, 2, 3],
       [5, 3, 4],
       [3, 4, 3],
       [5, 8, 8]])