In [1]:
import numpy as np

In [ ]:
class geneticAlgorithm:
    def __init__(self, objective = None, size = 100, dimension = 1, limits = [-100,100], max_gen = 100) -> None:
        self.population_size = size
        self.dimension = dimension
        self.max_gen = max_gen
        if len(limits) == 2 and type(limits[0]) in (int, float):
            self.limits = [limits]*dimension
        elif len(limits) == dimension:
            self.limits = limits
        else: raise Exception("LIMITS")

        self.recombination_types = {
            "mean":self.__rec_mean
        }
        if not objective: self.obj = self.__default_obj
        self.population = np.random.rand(self.population_size, self.dimension)


    def __default_obj(X):
        return np.sum(X**2)


    def __recombination(self, rec_type = 'mean'):
        rec = self.recombination_types[rec_type]
        new_population = np.zeros(self.population_size, self.dimension)
        for i in range(self.population_size):
            r = np.random.randint(0,self.population_size)
            new_population[i,:] = rec(self.population[i,:], self.population[r,:])
        return new_population

    
    def selection(self, new_population):
        temp_pop = np.concatenate((self.population, new_population), axis=0)
        objective = np.array([self.obj(temp_pop[i]) for i in temp_pop])
        index = np.argsort(objective)
        temp_pop = temp_pop[index]
        self.population = temp_pop[:self.population_size,:]

    def evolve(self, recombination = 'mean'):
        new_pop = self.__recombination(recombination)
        self.selection
    
    def __rec_mean(self,a,b):
        return (a + b)/2

function POPnovo = cruzamento(POP,xmin,xmax)
    tipo = 3;

    [tamPOP, numVAR] = size(POP);
    
    POPnovo = zeros(tamPOP,numVAR);

    switch tipo
        case 1
            for i = 1:tamPOP
                r = randperm(tamPOP,1);
                POPnovo(i) = (POP(i) + POP(r))/2;
            end
        case 2
            for i = 1:tamPOP
                r = randperm(tamPOP,1);
                POPnovo(i) = POP(i) + rand * (POP(r) - POP(i));
            end
        case 3
            for i = 1:tamPOP
                r = randperm(tamPOP,1);
                POPnovo(i) = POP(i) + (2 * rand - 0.5) * (POP(r) - POP(i));
            end
    end
            
    POPnovo = max(POPnovo,xmin);
    POPnovo = min(POPnovo,xmax);
end


In [13]:
pop = np.array([[1,2,3,4,5],[11,12,13,14,15],[36,37,38,39,40]],dtype="float64")

In [14]:
pop[1,:] = pop[1,:]/2.0

In [22]:
len(pop)

3

In [31]:
a = np.random.rand(2,3)
a

array([[0.48355967, 0.46502444, 0.2929519 ],
       [0.54565727, 0.76924294, 0.04387315]])

In [32]:
b = np.random.rand(2,3)
b

array([[0.58339043, 0.57955623, 0.71388534],
       [0.4428355 , 0.72288861, 0.65334513]])

In [35]:
c = np.concatenate((a,b),axis=0)

In [36]:
c

array([[0.48355967, 0.46502444, 0.2929519 ],
       [0.54565727, 0.76924294, 0.04387315],
       [0.58339043, 0.57955623, 0.71388534],
       [0.4428355 , 0.72288861, 0.65334513]])

In [52]:
a = np.random.randint(0,1000,101)

In [53]:
b = np.argsort(a)

In [6]:
b = np.array([1,2,3,0])

In [61]:
c

array([[0.48355967, 0.46502444, 0.2929519 ],
       [0.54565727, 0.76924294, 0.04387315],
       [0.58339043, 0.57955623, 0.71388534],
       [0.4428355 , 0.72288861, 0.65334513]])

In [63]:
d = c[b]

In [64]:
d[:2,:]

array([[0.54565727, 0.76924294, 0.04387315],
       [0.58339043, 0.57955623, 0.71388534]])

In [9]:
np.sum(b**3)

36