In [1]:
import numpy as np
from matplotlib import pyplot as plt, animation as ani

In [3]:
a = np.array([[1,2,3],[3,4,5]])
a.shape

(2, 3)

In [ ]:
def main():
    pop_size = 40
    pop_dimension = 5
    max_generations = 1000
    limits = [-100,100]
    population = limits[0] + np.random.rand(pop_size,pop_dimension) * (limits[1]-limits[0])

In [26]:
def paraboloid(X):
    return np.sum(X**2,axis=1)
    
def rastrigin(X):
    dim = X.shape[1]
    return 10*dim + np.sum(X**2-10*np.cos(2*np.pi*X),axis=1)

In [ ]:
def mutation(population, mut_type, width=2, offset=0.5):
    pop_size, pop_dim = population.shape
    r2 = width*np.random.rand(pop_size,pop_dim)-offset
    new_population = population + r2
    return new_population

In [ ]:
def recombination(population, rec_type='rand_between', width=2, offset=0.5):
    pop_size, pop_dim = population.shape
    if rec_type == 'mean':
        r1 = np.random.randint(0,pop_size,pop_size)
        new_population = (population + population[r1])/2
    if rec_type == 'rand_between':
        rec_type = 'window_offset'
        width = 1
        offset = 0
    if rec_type == 'window_offset':
        r1 = np.random.randint(0,pop_size,pop_size)
        r2 = width*np.random.rand(pop_size,pop_dim)-offset
        new_population = population + r2*(population[r1]-population)
    else: 
        Warning("No recombination in execution")
        new_population = population
    return new_population

In [ ]:
def selection(objective, pop_size, sel_type):
    if sel_type == 'elitism':
        index = np.argsort(objective)
        index = index[:pop_size]
    elif sel_type == 'tournment':
        r1 = np.random.randint(0,len(objective),pop_size)
        r2 = np.random.randint(0,len(objective),pop_size)
        lesser = objective[r1] <= objective[r2]
        index = np.concatenate((r1[lesser], r2[lesser.__invert__()]))
    elif sel_type == 'roulette':
        pass 
    else: index = selection(objective,pop_size,sel_type='elitism')
    return index


In [84]:
a = np.random.rand(5,5)

In [85]:
b = a<0.5

In [89]:
b

array([[ True,  True, False,  True, False],
       [False,  True, False,  True,  True],
       [False, False, False,  True, False],
       [ True, False,  True, False,  True],
       [False, False, False, False,  True]])

In [88]:
b.__invert__()

array([[False, False,  True, False,  True],
       [ True, False,  True, False, False],
       [ True,  True,  True, False,  True],
       [False,  True, False,  True, False],
       [ True,  True,  True,  True, False]])

In [44]:
a = np.random.rand(50,1)

In [83]:
r1 = np.random.randint(0,50,2)
r1

array([44,  5])

In [55]:
r2 = r1[:10]
r3 = r1[10:]

In [80]:
len(a)

5

In [58]:
r3

array([ 2,  6,  7,  4, 15,  9, 19, 18,  5, 14])

In [59]:
a = np.random.rand(20,1)

In [73]:
r3 = r3[1:]

In [74]:
b = a[r2]>=a[r3]

ValueError: operands could not be broadcast together with shapes (10,1) (9,1) 

In [62]:
b

array([[ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True]])

In [68]:
R = np.concatenate((r2[b.flatten()], r3[b.flatten() == False]))

In [70]:
a[R]

array([[0.2453841 ],
       [0.20404407],
       [0.9753992 ],
       [0.62842512],
       [0.6808933 ],
       [0.94953492],
       [0.96878176],
       [0.3006371 ],
       [0.72335942],
       [0.96536625]])

In [71]:
a

array([[0.94953492],
       [0.20404407],
       [0.07807974],
       [0.62842512],
       [0.11267865],
       [0.10569176],
       [0.3006371 ],
       [0.72335942],
       [0.6808933 ],
       [0.96536625],
       [0.17891027],
       [0.39043151],
       [0.9753992 ],
       [0.2453841 ],
       [0.40788544],
       [0.72859856],
       [0.09294021],
       [0.96878176],
       [0.4465635 ],
       [0.59793365]])