In [1]:
import numpy as np

In [2]:
def rastrigin(X):
    shape = X.shape
    if len(shape)>1:
        return 10*shape[1] + np.sum((X+1)**2-10*np.cos(2*np.pi*(X+1)),axis=1)
    else: return 10 + np.sum(X**2-10*np.cos(2*np.pi*X))

In [3]:
dim = 3
pop_size = 5
population = np.random.rand(pop_size,dim)
i = 2

In [4]:
for i in range(pop_size):
    C = np.random.rand(pop_size,1)+0.5
    locked = np.random.randint(dim)
    r1,r2,r3 = np.random.permutation(pop_size)[:3]
    child = population[r1] + C*(population[r3]-population[r2])
    rand = np.random.rand(dim)<0.5
    rand[locked] = False
    child[rand] = population[i][rand]
    if rastrigin(child) <= rastrigin(population[i]):
        population[i] = child

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3

In [22]:
population = np.random.rand(9,5)

In [23]:
np.mean(population,axis=0)

array([0.41512383, 0.74447701, 0.47950388, 0.43115136, 0.43287282])

In [24]:
population

array([[0.0367378 , 0.74500044, 0.47297676, 0.0176741 , 0.44879946],
       [0.05618668, 0.8998495 , 0.0954391 , 0.13523493, 0.17795463],
       [0.72551119, 0.40751685, 0.6004543 , 0.27188798, 0.1706663 ],
       [0.07124549, 0.35187839, 0.30943193, 0.94172835, 0.34596961],
       [0.82541542, 0.96120882, 0.51560101, 0.07963031, 0.25277047],
       [0.64704287, 0.77483436, 0.42180351, 0.08629112, 0.53629756],
       [0.6924065 , 0.64936958, 0.89624698, 0.75068546, 0.93457339],
       [0.6501479 , 0.99689347, 0.52570956, 0.92415338, 0.97574092],
       [0.03142064, 0.91374171, 0.47787177, 0.67307665, 0.053083  ]])

In [10]:
(0.78575082+0.88944819+0.35731092+0.82868558+0.77480084)/5

0.7271992700000001

In [34]:
(population[np.random.randint(0,9,9)] + population)/2

array([[0.05399165, 0.54843942, 0.39120435, 0.47970123, 0.39738454],
       [0.35316729, 0.94837148, 0.31057433, 0.52969416, 0.57684778],
       [0.39837834, 0.37969762, 0.45494312, 0.60680817, 0.25831796],
       [0.39837834, 0.37969762, 0.45494312, 0.60680817, 0.25831796],
       [0.73778166, 0.97905114, 0.52065528, 0.50189184, 0.61425569],
       [0.35161478, 0.83734193, 0.25862131, 0.11076303, 0.3571261 ],
       [0.70895884, 0.52844321, 0.74835064, 0.51128672, 0.55261985],
       [0.64859539, 0.88586391, 0.47375654, 0.50522225, 0.75601924],
       [0.04380366, 0.9067956 , 0.28665544, 0.40415579, 0.11551882]])

In [37]:
np.random.rand(10,5)*2-0.5 * (population-)

array([[-0.10503588,  0.29704373, -0.02876543,  0.98041519,  0.41782855],
       [ 0.50450179,  0.24593872,  0.87820498, -0.20264211,  0.66512763],
       [ 0.94959674,  0.57073692, -0.17359714, -0.08996128,  0.41611145],
       [ 0.3190873 , -0.05972157,  1.33107107,  0.74924367,  0.1794003 ],
       [-0.28582206,  0.37151676,  0.46219704,  1.27288236,  0.61980983],
       [ 0.00537766,  1.07054439,  0.95167745,  0.60846349,  0.30926508],
       [-0.48695588, -0.13568391,  1.01169267,  1.33142467,  0.69023809],
       [ 1.16310529,  1.33998764, -0.4700815 ,  1.05696211,  0.62053947],
       [ 0.08854106,  0.44584805, -0.3520469 ,  1.18429745, -0.07731344],
       [-0.07489884,  0.88103778,  1.18418033,  0.16061071,  1.28477709]])

In [40]:
population

array([[0.0367378 , 0.74500044, 0.47297676, 0.0176741 , 0.44879946],
       [0.05618668, 0.8998495 , 0.0954391 , 0.13523493, 0.17795463],
       [0.72551119, 0.40751685, 0.6004543 , 0.27188798, 0.1706663 ],
       [0.07124549, 0.35187839, 0.30943193, 0.94172835, 0.34596961],
       [0.82541542, 0.96120882, 0.51560101, 0.07963031, 0.25277047],
       [0.64704287, 0.77483436, 0.42180351, 0.08629112, 0.53629756],
       [0.6924065 , 0.64936958, 0.89624698, 0.75068546, 0.93457339],
       [0.6501479 , 0.99689347, 0.52570956, 0.92415338, 0.97574092],
       [0.03142064, 0.91374171, 0.47787177, 0.67307665, 0.053083  ]])

In [39]:
population[:,1]

array([0.74500044, 0.8998495 , 0.40751685, 0.35187839, 0.96120882,
       0.77483436, 0.64936958, 0.99689347, 0.91374171])

In [42]:
np.random.permutation([[1,2,3,4,5],[6,7,8,9,8]])

array([[6, 7, 8, 9, 8],
       [1, 2, 3, 4, 5]])

In [68]:
np.random.randint(0,10,10)

array([9, 7, 2, 7, 4, 4, 1, 9, 3, 8])

In [69]:
np.random.rand(2)

array([0.38861907, 0.90785935])

In [12]:
np.random.normal(0.5,0.1,(20,5))

array([[0.46600891, 0.55271797, 0.53346319, 0.53731927, 0.47946438],
       [0.49490744, 0.48987445, 0.53524697, 0.35934825, 0.57568239],
       [0.59127985, 0.5434972 , 0.56820022, 0.54198843, 0.52758775],
       [0.47166415, 0.48084484, 0.34273839, 0.52060126, 0.39925408],
       [0.33237635, 0.50778321, 0.31735483, 0.4032507 , 0.37634854],
       [0.45441717, 0.33043517, 0.57319339, 0.39493058, 0.58404817],
       [0.62762071, 0.45226337, 0.61311817, 0.34869557, 0.47400219],
       [0.5003567 , 0.46304637, 0.43073093, 0.18143872, 0.27018989],
       [0.47167173, 0.30580483, 0.56709449, 0.42342309, 0.42726474],
       [0.57210432, 0.61013401, 0.61761135, 0.57175888, 0.57703676],
       [0.5057867 , 0.4465151 , 0.47570921, 0.5212802 , 0.35462232],
       [0.56702827, 0.59797889, 0.67471704, 0.70864661, 0.76330118],
       [0.3281264 , 0.62993276, 0.4177813 , 0.31709863, 0.47579029],
       [0.73279019, 0.41482007, 0.34866397, 0.46469905, 0.70121294],
       [0.47302656, 0.53905025, 0.

In [16]:
np.random.standard_cauchy(10)

array([ -0.23101201,   0.63454305,   0.39484216,   1.39232763,
       -10.9983117 ,  -8.42653029,  10.23269293,  -0.64578699,
         0.26543347,   1.57819201])

In [17]:
from scipy.stats import cauchy

In [28]:
cauchy.rvs(loc=0.5,scale=0.1)

0.2443691355342909

In [36]:
max(min(cauchy.rvs(loc=0.5,scale=0.1),1),0)

0.31595413243294684

In [37]:
import statistics as stats

In [40]:
np.random.permutation(10)[:1]

array([9])

In [41]:
from scipy.stats import cauchy

In [47]:
cauchy.rvs(loc=0.5,scale=0.1,size=(10,5))

array([[ 0.8576084 ,  0.62175965,  0.48819047,  0.70195245,  0.88214211],
       [ 0.50849727,  0.48802045,  0.48923734,  1.67808188, -0.26073161],
       [ 0.94371449,  0.47051365,  0.45797026,  1.37946379,  0.82872758],
       [-9.38502072,  0.40521922,  0.6098599 ,  0.39893282,  0.52356793],
       [-0.9187991 ,  0.37765045,  0.569767  ,  0.50522585, -0.08036803],
       [ 0.47848477, -0.39928616,  0.37782756,  0.52175081,  0.5614777 ],
       [ 0.49571638,  0.46431295,  0.4627128 ,  0.46732069,  0.63350903],
       [ 8.24579475,  0.36928822,  0.38581423,  0.50092656,  0.1866291 ],
       [ 1.13075945,  0.58178071,  0.80638203,  0.56044282,  0.44451084],
       [ 0.6658003 ,  1.98038117,  0.6824504 ,  0.4640134 ,  0.73650487]])

In [49]:
a = [(1,2,3),(1,2,3),(1,2,3),(1,2,3),(1,2,3)]

In [51]:
scr = np.array(a)[:,0]

In [58]:
dd = np.array(a)[:,1]*5

In [52]:
scr

array([1, 1, 1, 1, 1])

In [59]:
np.sum(scr/np.sum(scr)*dd)

10.0

In [56]:
scr/np.sum(scr)

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [57]:
dd

array([2, 2, 2, 2, 2])

In [63]:
np.random.Generator.permutation(, axis=0)

TypeError: descriptor 'permutation' for 'numpy.random._generator.Generator' objects doesn't apply to a 'list' object

In [64]:
rng = np.random.default_rng()
rng.permutation(10)

array([6, 3, 4, 1, 2, 9, 5, 8, 0, 7])

In [73]:
rng.permutation(10,2)

array([7, 5, 6, 1, 0, 2, 9, 4, 8, 3])

In [109]:
b = np.random.randint(0,5,(1,10))
b

array([[1, 1, 2, 4, 3, 0, 1, 3, 4, 1]])

In [128]:
a = np.ones((10,5)) == 1
a[np.arange(10),b] = False
a

array([[ True, False,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True, False,  True],
       [False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False],
       [ True, False,  True,  True,  True]])

In [115]:
c = np.random.rand(5,3)
c

array([[0.59284559, 0.65432778, 0.39566125],
       [0.07058207, 0.55991727, 0.01231046],
       [0.73020344, 0.96329901, 0.36831344],
       [0.13946909, 0.17582876, 0.16653524],
       [0.69215302, 0.44457617, 0.52654126]])

In [126]:
c[np.arange(5),np.array([1,1,2,2,0])]=0

In [132]:
c<np.array([[0.5] for _ in range(5)])

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [ ]:
np.random.rand()