In [1]:
import numpy as np

In [3]:
def rastrigin(X):
    offset = -1
    shape = X.shape
    if len(shape)>1:
        return 10*shape[1] + np.sum((X+offset)**2-10*np.cos(2*np.pi*(X+offset)),axis=1)
    else: return 10*shape[0] + np.sum((X+offset)**2-10*np.cos(2*np.pi*(X+offset)))

In [4]:
f = rastrigin

In [5]:
pop_size        = 20
dim             = 2
xmin, xmax      = -5.12, 5.12
max_epoch       = 1000
v_max           = (xmax-xmin) / 20

pop             = xmin + np.random.rand(pop_size,dim) * (xmax-xmin)
f_pop           = f(pop)
v               = v_max * (2*np.random.rand(pop_size,dim)-1)

inertia, attraction_pbest, attraction_gbest = 1, 0.3, 0.2

pbest          = pop.copy()
f_pbest         = f_pop.copy()
gbest          = pop[np.argmin(f_pop)]
f_gbest         = f_pop[np.argmin(f_pop)]


for _ in range(max_epoch):
    pop                     = pop + v 
    pop[pop>xmax]           = xmax
    pop[pop<xmin]           = xmin
    f_pop                   = f(pop)
    f_pbest[f_pbest>f_pop]  = f_pop[f_pbest>f_pop]
    pbest[f_pbest>f_pop]    = pop[f_pbest>f_pop]
    argbest                 = np.argmin(f_pbest)
    gbest                   = pbest[argbest]
    f_gbest                 = f_pbest[argbest]

    v = inertia * v + attraction_pbest * (pbest - pop) + attraction_gbest(gbest - pop)

    v[v>v_max]              = v_max
    v[v<-v_max]             = -v_max





In [7]:
a = np.random.randint(0,100,(5,4))

In [10]:
b = np.arange(4)+1

In [13]:
a

array([[53, 11, 82, 34],
       [23, 22, 21, 50],
       [32, 40, 14, 18],
       [77, 62, 96, 96],
       [21, 19, 68, 42]])

In [12]:
a/b

array([[53.        ,  5.5       , 27.33333333,  8.5       ],
       [23.        , 11.        ,  7.        , 12.5       ],
       [32.        , 20.        ,  4.66666667,  4.5       ],
       [77.        , 31.        , 32.        , 24.        ],
       [21.        ,  9.5       , 22.66666667, 10.5       ]])

In [11]:
b

array([1, 2, 3, 4])

In [14]:
def griewank(X):
    offset = 0
    shape = X.shape
    if len(shape)>1:
        return np.sum((X+offset)**2/4000,axis=1) - np.prod(np.cos((X+offset)/np.sqrt(np.arange(shape[1])+1)),axis=1) + 1
    else: return np.sum((X+offset)**2/4000) - np.prod(np.cos((X+offset)/np.sqrt(np.arange(shape[0])+1))) + 1

In [ ]:
np.arange()

In [17]:
griewank()

0.9059004610458478