In [1]:
import numpy as np

In [2]:
X = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
np.sum(X)

78

In [4]:
np.sum(X,axis=1)

array([10, 26, 42])

In [14]:
a = np.random.rand(5,3)
a

array([[0.79250425, 0.90517632, 0.89619067],
       [0.71844875, 0.38421697, 0.58275849],
       [0.35456546, 0.33659149, 0.06726576],
       [0.33612697, 0.80138146, 0.27374223],
       [0.6957537 , 0.26810661, 0.58322789]])

In [30]:
np.take(a,range(),axis=0)

SyntaxError: invalid syntax (1774032577.py, line 1)

In [27]:
a[[0,1,2,3,4]]

array([[0.79250425, 0.90517632, 0.89619067],
       [0.71844875, 0.38421697, 0.58275849],
       [0.35456546, 0.33659149, 0.06726576],
       [0.33612697, 0.80138146, 0.27374223],
       [0.6957537 , 0.26810661, 0.58322789]])

In [ ]:
np.take(a,())

In [32]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
for i in range(-10,18):
    print(np.random.randint(4))

3
2
2
1
3
0
0
0
3
1
3
2
0
3
1
2
3
1
0
0
0
3
2
2
3
3
0
3
